version: '3'

services:
  app:
    build: .
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    user: "node"
    depends_on:
      - redis

  redis:
    image: redis:6.2.6-alpine3.14